apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - args:
            - npm
            - start
          image: lijozech12/jenkins-k8s-testproject:latest
          name: app
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
