pipeline{
    agent any
    stages{
        stage('Checkout from Git'){
            steps{
                git branch: 'main', url: 'https://github.com/lijozech-12/Jenkins-k8s-sample-website.git'
            }
        }
        stage('checking contents'){
            steps{
                sh "ls -la"
            }
        }
        // stage('Applying configmap'){
        //     steps{
        //         sh "kubectl apply -f Kuberenetes_files/app-cm0-configmap.yaml"
        //     }
        // }
        stage('Applying deployment'){
            steps{
                sh "kubectl apply -f Kuberenetes_files/app-deployment.yaml"
            }
        }
        stage('Applying service'){
            steps{
                sh "kubectl apply -f Kuberenetes_files/app-service.yaml"
            }
        }
    }
}